menu: 
  works: /categories/works
  articles: /categories/articles
socialLinks:
  github: https://github.com/adityarahmanda
  linkedin: https://www.linkedin.com/in/adityarahmanda
  instagram: https://www.instagram.com/adit.rahmanda